subprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
        maven {
            name = 'PaperMC'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            name = 'Fzzy'
            url = 'https://maven.fzzyhmstrs.me/'
        }
        maven {
            name = 'Terraformers'
            url = 'https://maven.terraformersmc.com/releases/'
        }
        maven {
            name = 'Nyon'
            url = 'https://repo.nyon.dev/releases'
        }
    }

    plugins.withId('java') {
        java {
            sourceCompatibility = JavaVersion.VERSION_25
            targetCompatibility = JavaVersion.VERSION_25
            withSourcesJar()
        }

        tasks.withType(JavaCompile).configureEach {
            it.options.encoding = 'UTF-8'
            it.options.release = 25
        }

        jar {
            def projectName = rootProject.name
            inputs.property 'projectName', projectName

            from(rootProject.file('LICENSE')) {
                rename { "${it}_$projectName" }
            }
        }
    }
}
