org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod
version=0.1.0-beta.2+26.2
group=zapmc.quicify

# Toolchain
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_api_version=0.158.0+26.2
fzzy_config_version=0.7.6+26.2
fzzy_config_neoforge_version=0.7.6+26.2+neoforge
neoforge_version=26.2.0.69
moddev_version=2.0.144
junit_version=6.1.3
# must match the Netty version bundled with minecraft_version
netty_quic_version=4.2.15.Final
zstd_version=1.5.7-15
